https://cs210groupprojectcreditriskprediction.wordpress.com/

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from datetime import datetime
import seaborn as sns
from datetime import datetime

import warnings
warnings.filterwarnings('ignore')

sns.set(style="darkgrid")

%matplotlib inline

In [2]:
from os.path import join
from pprint import pprint

In [3]:
df = pd.read_csv(join("loan.csv"))

In [4]:
df.head()   #an outline for the dataset

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
n_rows, n_columns = df.shape  # get the shape of dataframe
print("number of rows: {}, number of columns: {}".format(n_rows, n_columns))

number of rows: 2260668, number of columns: 145

In [6]:
df.dtypes  # data types of each column

id                                            float64
member_id                                     float64
loan_amnt                                       int64
funded_amnt                                     int64
funded_amnt_inv                               float64
term                                           object
int_rate                                      float64
installment                                   float64
grade                                          object
sub_grade                                      object
emp_title                                      object
emp_length                                     object
home_ownership                                 object
annual_inc                                    float64
verification_status                            object
issue_d                                        object
loan_status                                    object
pymnt_plan                                     object
url                                           float64
desc                                           object
purpose                                        object
title                                          object
zip_code                                       object
addr_state                                     object
dti                                           float64
delinq_2yrs                                   float64
earliest_cr_line                               object
inq_last_6mths                                float64
mths_since_last_delinq                        float64
mths_since_last_record                        float64
                                               ...
sec_app_open_acc                              float64
sec_app_revol_util                            float64
sec_app_open_act_il                           float64
sec_app_num_rev_accts                         float64
sec_app_chargeoff_within_12_mths              float64
sec_app_collections_12_mths_ex_med            float64
sec_app_mths_since_last_major_derog           float64
hardship_flag                                  object
hardship_type                                  object
hardship_reason                                object
hardship_status                                object
deferral_term                                 float64
hardship_amount                               float64
hardship_start_date                            object
hardship_end_date                              object
payment_plan_start_date                        object
hardship_length                               float64
hardship_dpd                                  float64
hardship_loan_status                           object
orig_projected_additional_accrued_interest    float64
hardship_payoff_balance_amount                float64
hardship_last_payment_amount                  float64
disbursement_method                            object
debt_settlement_flag                           object
debt_settlement_flag_date                      object
settlement_status                              object
settlement_date                                object
settlement_amount                             float64
settlement_percentage                         float64
settlement_term                               float64
Length: 145, dtype: object

In [7]:
df = df.iloc[::20] #took data 20 by 20 , starting from index 0 , to get a better clustered data

In [8]:
df  #outline

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,10000,10000,10000.0,36 months,13.56,339.65,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,20000,20000,20000.0,36 months,12.98,673.69,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
60,NaN,NaN,25000,25000,25000.0,60 months,15.02,595.02,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,22400,22400,22400.0,60 months,16.14,546.40,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,30000,30000,30000.0,36 months,22.35,1151.16,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
120,NaN,NaN,32000,32000,32000.0,60 months,14.47,752.41,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
140,NaN,NaN,24000,24000,24000.0,60 months,11.31,525.54,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
160,NaN,NaN,15000,15000,15000.0,60 months,14.47,352.69,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
180,NaN,NaN,25000,25000,25000.0,60 months,15.02,595.02,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
200,NaN,NaN,7075,7075,7075.0,36 months,23.40,275.35,E,E1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
220,NaN,NaN,15000,15000,15000.0,60 months,14.47,352.69,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
240,NaN,NaN,27975,27975,27975.0,36 months,14.47,962.52,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
260,NaN,NaN,10000,10000,10000.0,36 months,11.80,331.19,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
280,NaN,NaN,15000,15000,15000.0,60 months,18.94,388.62,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
300,NaN,NaN,16000,16000,16000.0,36 months,10.33,518.76,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
320,NaN,NaN,36950,36950,36950.0,60 months,11.80,818.21,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
340,NaN,NaN,21000,21000,21000.0,60 months,15.02,499.81,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
360,NaN,NaN,5000,5000,5000.0,36 months,13.56,169.83,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
380,NaN,NaN,12000,12000,12000.0,36 months,11.80,397.43,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
400,NaN,NaN,6025,6025,6025.0,36 months,19.92,223.67,D,D3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
420,NaN,NaN,12000,12000,12000.0,36 months,6.46,367.57,A,A1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
440,NaN,NaN,20000,20000,20000.0,60 months,16.14,487.86,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
460,NaN,NaN,3000,3000,3000.0,36 months,24.37,118.29,E,E2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
480,NaN,NaN,4000,4000,4000.0,36 months,7.02,123.55,A,A2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
500,NaN,NaN,6000,6000,6000.0,36 months,17.97,216.83,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
520,NaN,NaN,4800,4800,4800.0,36 months,10.72,156.52,B,B2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
540,NaN,NaN,40000,40000,40000.0,60 months,13.56,921.64,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
560,NaN,NaN,4000,4000,4000.0,36 months,7.02,123.55,A,A2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
580,NaN,NaN,15000,15000,15000.0,36 months,7.02,463.30,A,A2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260080,NaN,NaN,12000,12000,12000.0,60 months,13.59,276.68,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260100,NaN,NaN,5100,5100,5100.0,36 months,19.03,187.03,D,D3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260120,NaN,NaN,10000,10000,10000.0,60 months,16.02,243.29,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260140,NaN,NaN,12000,12000,12000.0,60 months,18.06,305.12,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260160,NaN,NaN,25000,25000,25000.0,60 months,12.62,563.98,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260180,NaN,NaN,12000,12000,12000.0,36 months,5.32,361.38,A,A1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260200,NaN,NaN,4700,4700,4700.0,36 months,7.97,147.22,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260220,NaN,NaN,5000,5000,5000.0,36 months,11.99,166.05,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260240,NaN,NaN,10000,10000,10000.0,36 months,9.44,320.05,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260260,NaN,NaN,20000,20000,20000.0,36 months,9.44,640.10,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260280,NaN,NaN,20000,20000,20000.0,36 months,7.97,626.46,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260300,NaN,NaN,4200,4200,4200.0,36 months,22.91,162.39,E,E1,...,NaN,NaN,Cash,Y,Oct-2018,ACTIVE,Sep-2018,1660.0,40.02,6.0
2260320,NaN,NaN,30000,30000,30000.0,36 months,16.02,1055.01,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260340,NaN,NaN,16200,16200,16200.0,36 months,23.88,634.56,E,E2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260360,NaN,NaN,21800,21800,21800.0,36 months,30.75,934.43,F,F5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260380,NaN,NaN,11200,11200,11200.0,36 months,9.44,358.46,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260400,NaN,NaN,16000,16000,16000.0,36 months,9.93,515.75,B,B2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260420,NaN,NaN,8500,8500,8500.0,36 months,9.93,274.00,B,B2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260440,NaN,NaN,35000,35000,35000.0,36 months,24.85,1388.82,E,E3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260460,NaN,NaN,20000,20000,20000.0,36 months,18.06,723.66,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260480,NaN,NaN,20000,20000,20000.0,36 months,10.91,653.93,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260500,NaN,NaN,15000,15000,14950.0,36 months,19.03,550.07,D,D3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260520,NaN,NaN,10000,10000,10000.0,36 months,18.06,361.83,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260540,NaN,NaN,16500,16500,16250.0,36 months,9.44,528.09,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260560,NaN,NaN,35000,35000,35000.0,36 months,19.03,1283.50,D,D3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260580,NaN,NaN,5000,5000,5000.0,36 months,22.91,193.32,E,E1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260600,NaN,NaN,20000,20000,20000.0,36 months,20.00,743.28,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260620,NaN,NaN,11600,11600,11600.0,36 months,17.09,414.10,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260640,NaN,NaN,20700,20700,20700.0,60 months,12.62,466.98,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260660,NaN,NaN,10000,10000,10000.0,36 months,12.62,335.12,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df = df.drop(df.columns[df.apply(lambda col: col.isnull().sum() >10000)], axis=1)   


#if the a data contains more than 100 null values of columns, we do not want to work on tahat data , as that row
#does not contain sufficient information to work on

In [10]:
df.iloc[20]   #a look at the 20th index :

loan_amnt                                        6025
funded_amnt                                      6025
funded_amnt_inv                                  6025
term                                        36 months
int_rate                                        19.92
installment                                    223.67
grade                                               D
sub_grade                                          D3
emp_title                                      Welder
emp_length                                   < 1 year
home_ownership                                   RENT
annual_inc                                      21600
verification_status                   Source Verified
issue_d                                      Dec-2018
loan_status                                   Current
pymnt_plan                                          n
purpose                                   credit_card
title                         Credit card refinancing
zip_code                                        021xx
addr_state                                         MA
dti                                              7.53
delinq_2yrs                                         0
earliest_cr_line                             Jul-2015
inq_last_6mths                                      1
open_acc                                            1
pub_rec                                             0
revol_bal                                        1171
revol_util                                       46.8
total_acc                                           3
initial_list_status                                 w
                                       ...
mo_sin_old_rev_tl_op                               36
mo_sin_rcnt_rev_tl_op                               4
mo_sin_rcnt_tl                                      4
mort_acc                                            0
mths_since_recent_bc                              NaN
num_accts_ever_120_pd                               0
num_actv_bc_tl                                      0
num_actv_rev_tl                                     1
num_bc_sats                                         0
num_bc_tl                                           1
num_il_tl                                           1
num_op_rev_tl                                       1
num_rev_accts                                       2
num_rev_tl_bal_gt_0                                 1
num_sats                                            1
num_tl_120dpd_2m                                    0
num_tl_30dpd                                        0
num_tl_90g_dpd_24m                                  0
num_tl_op_past_12m                                  1
pct_tl_nvr_dlq                                    100
percent_bc_gt_75                                  NaN
pub_rec_bankruptcies                                0
tax_liens                                           0
tot_hi_cred_lim                                  2500
total_bal_ex_mort                                1171
total_bc_limit                                      0
total_il_high_credit_limit                          0
hardship_flag                                       N
disbursement_method                              Cash
debt_settlement_flag                                N
Name: 400, Length: 86, dtype: object

In [11]:
df

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
0,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,...,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,N,Cash,N
20,10000,10000,10000.0,36 months,13.56,339.65,C,C1,NaN,< 1 year,...,80.0,1.0,0.0,48052.0,45972.0,11500.0,34852.0,N,Cash,N
40,20000,20000,20000.0,36 months,12.98,673.69,B,B5,FC,5 years,...,100.0,0.0,0.0,52000.0,39977.0,28700.0,18000.0,N,Cash,N
60,25000,25000,25000.0,60 months,15.02,595.02,C,C3,CFO,10+ years,...,0.0,1.0,0.0,100078.0,85514.0,12400.0,81178.0,N,Cash,N
80,22400,22400,22400.0,60 months,16.14,546.40,C,C4,Paramedic/ Fire Fighter,10+ years,...,25.0,0.0,0.0,253539.0,32070.0,28200.0,23364.0,N,Cash,N
100,30000,30000,30000.0,36 months,22.35,1151.16,D,D5,Supervisor,5 years,...,33.3,1.0,0.0,527120.0,98453.0,28600.0,101984.0,N,Cash,N
120,32000,32000,32000.0,60 months,14.47,752.41,C,C2,Teacher,10+ years,...,12.5,0.0,0.0,94609.0,73873.0,26800.0,60109.0,N,Cash,N
140,24000,24000,24000.0,60 months,11.31,525.54,B,B3,Bill Collector,1 year,...,100.0,0.0,0.0,175897.0,44431.0,14000.0,34597.0,N,Cash,N
160,15000,15000,15000.0,60 months,14.47,352.69,C,C2,Operation s director,10+ years,...,50.0,0.0,0.0,391104.0,65710.0,10900.0,59454.0,N,Cash,N
180,25000,25000,25000.0,60 months,15.02,595.02,C,C3,radiologic technologist,10+ years,...,25.0,0.0,0.0,246339.0,58866.0,45500.0,47139.0,N,Cash,N
200,7075,7075,7075.0,36 months,23.40,275.35,E,E1,NaN,NaN,...,66.7,0.0,0.0,21492.0,11000.0,4000.0,11492.0,N,Cash,N
220,15000,15000,15000.0,60 months,14.47,352.69,C,C2,"VP, Solutions Management",9 years,...,100.0,0.0,0.0,439690.0,92505.0,39800.0,11223.0,N,Cash,N
240,27975,27975,27975.0,36 months,14.47,962.52,C,C2,Conductor,10+ years,...,60.0,0.0,0.0,286525.0,45387.0,29500.0,25025.0,N,Cash,N
260,10000,10000,10000.0,36 months,11.80,331.19,B,B4,Carpenter,7 years,...,0.0,0.0,0.0,235420.0,60105.0,9600.0,64933.0,N,Cash,N
280,15000,15000,15000.0,60 months,18.94,388.62,D,D2,Teacher,10+ years,...,NaN,0.0,0.0,264850.0,13074.0,0.0,10000.0,N,Cash,N
300,16000,16000,16000.0,36 months,10.33,518.76,B,B1,Translator/linguistic,4 years,...,50.0,0.0,0.0,291221.0,46028.0,24000.0,31721.0,N,Cash,N
320,36950,36950,36950.0,60 months,11.80,818.21,B,B4,Director of Infrastructure Engineering,1 year,...,0.0,0.0,0.0,107000.0,61275.0,45000.0,58700.0,N,Cash,N
340,21000,21000,21000.0,60 months,15.02,499.81,C,C3,Admission Counsellor,4 years,...,0.0,0.0,0.0,100200.0,59030.0,43200.0,57000.0,N,Cash,N
360,5000,5000,5000.0,36 months,13.56,169.83,C,C1,CNA,2 years,...,0.0,0.0,0.0,27386.0,16929.0,9500.0,14886.0,N,Cash,N
380,12000,12000,12000.0,36 months,11.80,397.43,B,B4,NaN,NaN,...,57.1,0.0,0.0,60102.0,37337.0,16400.0,39402.0,N,Cash,N
400,6025,6025,6025.0,36 months,19.92,223.67,D,D3,Welder,< 1 year,...,NaN,0.0,0.0,2500.0,1171.0,0.0,0.0,N,Cash,N
420,12000,12000,12000.0,36 months,6.46,367.57,A,A1,Social Studies Teacher,6 years,...,33.3,0.0,0.0,97074.0,40761.0,16300.0,68174.0,N,Cash,N
440,20000,20000,20000.0,60 months,16.14,487.86,C,C4,Instructor/Transporter/Job Coach,4 years,...,50.0,0.0,0.0,131547.0,34891.0,15000.0,30647.0,N,Cash,N
460,3000,3000,3000.0,36 months,24.37,118.29,E,E2,Conductor,10+ years,...,100.0,0.0,0.0,279700.0,50416.0,48700.0,0.0,N,Cash,N
480,4000,4000,4000.0,36 months,7.02,123.55,A,A2,Receptionist,8 years,...,0.0,0.0,0.0,73200.0,13539.0,60200.0,12000.0,N,Cash,N
500,6000,6000,6000.0,36 months,17.97,216.83,D,D1,Director of Fleet,5 years,...,66.7,0.0,0.0,453907.0,226523.0,46200.0,236720.0,N,Cash,N
520,4800,4800,4800.0,36 months,10.72,156.52,B,B2,Realtor,10+ years,...,100.0,0.0,0.0,100661.0,66460.0,10800.0,76361.0,N,Cash,N
540,40000,40000,40000.0,60 months,13.56,921.64,C,C1,Operations Manager,7 years,...,0.0,0.0,0.0,366902.0,121002.0,21700.0,120452.0,N,Cash,N
560,4000,4000,4000.0,36 months,7.02,123.55,A,A2,Biology professor,10+ years,...,25.0,0.0,0.0,55331.0,16584.0,24200.0,21731.0,N,Cash,N
580,15000,15000,15000.0,36 months,7.02,463.30,A,A2,NaN,< 1 year,...,10.0,0.0,0.0,162700.0,15844.0,56800.0,0.0,N,Cash,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260080,12000,12000,12000.0,60 months,13.59,276.68,C,C2,sales,10+ years,...,0.0,0.0,0.0,80599.0,30468.0,27500.0,25799.0,N,Cash,N
2260100,5100,5100,5100.0,36 months,19.03,187.03,D,D3,"Carrier, and field representative",4 years,...,70.0,1.0,0.0,63809.0,47254.0,25400.0,30109.0,N,Cash,N
2260120,10000,10000,10000.0,60 months,16.02,243.29,C,C5,Fiber Splicer,2 years,...,33.3,0.0,0.0,225919.0,29422.0,16700.0,42557.0,N,Cash,N
2260140,12000,12000,12000.0,60 months,18.06,305.12,D,D2,billing analist,2 years,...,50.0,0.0,0.0,18900.0,12895.0,17800.0,0.0,N,Cash,N
2260160,25000,25000,25000.0,60 months,12.62,563.98,C,C1,Management Services Officer I,10+ years,...,14.3,0.0,0.0,118033.0,58026.0,38000.0,54433.0,N,Cash,N
2260180,12000,12000,12000.0,36 months,5.32,361.38,A,A1,International Managing Director,10+ years,...,0.0,0.0,0.0,88500.0,9022.0,68500.0,0.0,N,Cash,N
2260200,4700,4700,4700.0,36 months,7.97,147.22,A,A5,Sales Trainer,3 years,...,50.0,0.0,0.0,70150.0,34820.0,18700.0,44550.0,N,Cash,N
2260220,5000,5000,5000.0,36 months,11.99,166.05,B,B5,WARRANTY ADMINISTRATOR,3 years,...,16.7,1.0,0.0,82720.0,51836.0,22600.0,49720.0,N,Cash,N
2260240,10000,10000,10000.0,36 months,9.44,320.05,B,B1,Welder fitter leader,10+ years,...,0.0,1.0,0.0,52279.0,28844.0,6800.0,41979.0,N,Cash,N
2260260,20000,20000,20000.0,36 months,9.44,640.10,B,B1,Director,10+ years,...,100.0,0.0,0.0,559157.0,8922.0,9100.0,0.0,N,Cash,N
2260280,20000,20000,20000.0,36 months,7.97,626.46,A,A5,Site Reliability Engineer,< 1 year,...,50.0,0.0,0.0,371571.0,67908.0,36400.0,88171.0,N,Cash,N
2260300,4200,4200,4200.0,36 months,22.91,162.39,E,E1,porter,7 years,...,33.3,0.0,0.0,19500.0,10177.0,10100.0,0.0,N,Cash,Y
2260320,30000,30000,30000.0,36 months,16.02,1055.01,C,C5,Medicare D Advisor,3 years,...,100.0,0.0,0.0,73549.0,43247.0,17500.0,48249.0,N,Cash,N
2260340,16200,16200,16200.0,36 months,23.88,634.56,E,E2,Mechanic,5 years,...,50.0,0.0,0.0,211011.0,5961.0,6500.0,2525.0,N,Cash,N
2260360,21800,21800,21800.0,36 months,30.75,934.43,F,F5,Shop manager,6 years,...,33.3,0.0,0.0,366044.0,16752.0,16000.0,4993.0,N,Cash,N
2260380,11200,11200,11200.0,36 months,9.44,358.46,B,B1,Phase 1 Tester,10+ years,...,0.0,0.0,0.0,19700.0,5435.0,17300.0,0.0,N,Cash,N
2260400,16000,16000,16000.0,36 months,9.93,515.75,B,B2,Legal secretary,10+ years,...,41.7,0.0,0.0,386477.0,115065.0,105600.0,71077.0,N,Cash,N
2260420,8500,8500,8500.0,36 months,9.93,274.00,B,B2,Installer technician,4 years,...,20.0,1.0,0.0,76526.0,32616.0,21300.0,30726.0,N,Cash,N
2260440,35000,35000,35000.0,36 months,24.85,1388.82,E,E3,NaN,NaN,...,100.0,1.0,0.0,313855.0,29096.0,13000.0,21419.0,N,Cash,N
2260460,20000,20000,20000.0,36 months,18.06,723.66,D,D2,Member Service Rep,3 years,...,75.0,0.0,0.0,47233.0,31641.0,16400.0,19933.0,N,Cash,N
2260480,20000,20000,20000.0,36 months,10.91,653.93,B,B4,Accountant,10+ years,...,14.3,0.0,0.0,52600.0,21224.0,44200.0,0.0,N,Cash,N
2260500,15000,15000,14950.0,36 months,19.03,550.07,D,D3,Office Manager / Exec. Assistant,10+ years,...,66.7,1.0,0.0,76830.0,34299.0,25100.0,37530.0,N,Cash,N
2260520,10000,10000,10000.0,36 months,18.06,361.83,D,D2,Conductor,10+ years,...,60.0,2.0,0.0,7700.0,4986.0,6900.0,0.0,N,Cash,N
2260540,16500,16500,16250.0,36 months,9.44,528.09,B,B1,Business Analyst,10+ years,...,20.0,0.0,0.0,297444.0,127028.0,14100.0,93826.0,N,Cash,N
2260560,35000,35000,35000.0,36 months,19.03,1283.50,D,D3,NURSE SUPERVISOR,3 years,...,0.0,0.0,0.0,38454.0,9719.0,16000.0,13254.0,N,Cash,N
2260580,5000,5000,5000.0,36 months,22.91,193.32,E,E1,Teacher,4 years,...,71.4,0.0,0.0,31128.0,18912.0,11700.0,15228.0,N,Cash,N
2260600,20000,20000,20000.0,36 months,20.00,743.28,D,D4,Mechanical engineer,10+ years,...,100.0,1.0,0.0,131802.0,105517.0,7500.0,116502.0,N,Cash,N
2260620,11600,11600,11600.0,36 months,17.09,414.10,D,D1,doorman,8 years,...,33.3,0.0,0.0,43956.0,33442.0,21000.0,22956.0,N,Cash,N
2260640,20700,20700,20700.0,60 months,12.62,466.98,C,C1,Dental Assistant,10+ years,...,50.0,1.0,0.0,82200.0,33323.0,56500.0,16500.0,N,Cash,N
2260660,10000,10000,10000.0,36 months,12.62,335.12,C,C1,Administrator,5 years,...,75.0,0.0,0.0,13300.0,11695.0,13300.0,0.0,N,Cash,N

In [12]:
df["funded_amnt"] #funded amounts for each 20th index , staring from index 0

0           2500
20         10000
40         20000
60         25000
80         22400
100        30000
120        32000
140        24000
160        15000
180        25000
200         7075
220        15000
240        27975
260        10000
280        15000
300        16000
320        36950
340        21000
360         5000
380        12000
400         6025
420        12000
440        20000
460         3000
480         4000
500         6000
520         4800
540        40000
560         4000
580        15000
           ...
2260080    12000
2260100     5100
2260120    10000
2260140    12000
2260160    25000
2260180    12000
2260200     4700
2260220     5000
2260240    10000
2260260    20000
2260280    20000
2260300     4200
2260320    30000
2260340    16200
2260360    21800
2260380    11200
2260400    16000
2260420     8500
2260440    35000
2260460    20000
2260480    20000
2260500    15000
2260520    10000
2260540    16500
2260560    35000
2260580     5000
2260600    20000
2260620    11600
2260640    20700
2260660    10000
Name: funded_amnt, Length: 113034, dtype: int64

In [13]:
list(df.columns.values) #list of column names for better visiualisation

['loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'inq_last_6mths',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'last_credit_pull_d',
 'collections_12_mths_ex_med',
 'policy_code',
 'application_type',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'total_rev_hi_lim',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'hardship_flag',
 'disbursement_method',
 'debt_settlement_flag']

In [14]:
df = df[["loan_amnt","funded_amnt","term","int_rate","installment","sub_grade","emp_title","emp_length","home_ownership","annual_inc","issue_d","loan_status","dti","delinq_2yrs","inq_last_6mths","revol_util","total_bal_ex_mort"]]

In [15]:
df   #created a table containing only related columns with our project , dropping irrevalent columns.

,loan_amnt,funded_amnt,term,int_rate,installment,sub_grade,emp_title,emp_length,home_ownership,annual_inc,issue_d,loan_status,dti,delinq_2yrs,inq_last_6mths,revol_util,total_bal_ex_mort
0,2500,2500,36 months,13.56,84.92,C1,Chef,10+ years,RENT,55000.0,Dec-2018,Current,18.24,0.0,1.0,10.3,16901.0
20,10000,10000,36 months,13.56,339.65,C1,NaN,< 1 year,MORTGAGE,65000.0,Dec-2018,Current,10.62,0.0,1.0,74.0,45972.0
40,20000,20000,36 months,12.98,673.69,B5,FC,5 years,RENT,74800.0,Dec-2018,Current,23.50,0.0,0.0,88.4,39977.0
60,25000,25000,60 months,15.02,595.02,C3,CFO,10+ years,MORTGAGE,63500.0,Dec-2018,Current,27.52,0.0,0.0,41.0,85514.0
80,22400,22400,60 months,16.14,546.40,C4,Paramedic/ Fire Fighter,10+ years,OWN,56000.0,Dec-2018,Current,18.47,0.0,0.0,38.2,32070.0
100,30000,30000,36 months,22.35,1151.16,D5,Supervisor,5 years,MORTGAGE,100000.0,Dec-2018,Fully Paid,30.46,0.0,0.0,37.0,98453.0
120,32000,32000,60 months,14.47,752.41,C2,Teacher,10+ years,MORTGAGE,110000.0,Dec-2018,Current,26.11,0.0,0.0,43.0,73873.0
140,24000,24000,60 months,11.31,525.54,B3,Bill Collector,1 year,MORTGAGE,72000.0,Dec-2018,Current,21.12,0.0,0.0,79.1,44431.0
160,15000,15000,60 months,14.47,352.69,C2,Operation s director,10+ years,MORTGAGE,120000.0,Dec-2018,Current,13.58,0.0,0.0,69.5,65710.0
180,25000,25000,60 months,15.02,595.02,C3,radiologic technologist,10+ years,MORTGAGE,75000.0,Dec-2018,Current,32.93,0.0,0.0,66.2,58866.0
200,7075,7075,36 months,23.40,275.35,E1,NaN,NaN,RENT,19200.0,Dec-2018,Current,30.34,0.0,0.0,71.0,11000.0
220,15000,15000,60 months,14.47,352.69,C2,"VP, Solutions Management",9 years,RENT,280000.0,Dec-2018,Current,16.15,0.0,0.0,85.0,92505.0
240,27975,27975,36 months,14.47,962.52,C2,Conductor,10+ years,MORTGAGE,180000.0,Dec-2018,Current,11.47,0.0,0.0,66.8,45387.0
260,10000,10000,36 months,11.80,331.19,B4,Carpenter,7 years,MORTGAGE,80000.0,Dec-2018,Current,18.04,0.0,1.0,4.4,60105.0
280,15000,15000,60 months,18.94,388.62,D2,Teacher,10+ years,MORTGAGE,165000.0,Dec-2018,Current,3.07,0.0,1.0,20.6,13074.0
300,16000,16000,36 months,10.33,518.76,B1,Translator/linguistic,4 years,MORTGAGE,65000.0,Dec-2018,Current,15.27,0.0,0.0,39.4,46028.0
320,36950,36950,60 months,11.80,818.21,B4,Director of Infrastructure Engineering,1 year,RENT,284000.0,Dec-2018,Current,3.95,0.0,2.0,11.6,61275.0
340,21000,21000,60 months,15.02,499.81,C3,Admission Counsellor,4 years,MORTGAGE,51000.0,Dec-2018,Current,22.00,0.0,0.0,13.0,59030.0
360,5000,5000,36 months,13.56,169.83,C1,CNA,2 years,RENT,35140.0,Dec-2018,Current,7.89,0.0,1.0,17.6,16929.0
380,12000,12000,36 months,11.80,397.43,B4,NaN,NaN,RENT,55000.0,Dec-2018,Current,28.80,0.0,0.0,60.8,37337.0
400,6025,6025,36 months,19.92,223.67,D3,Welder,< 1 year,RENT,21600.0,Dec-2018,Current,7.53,0.0,1.0,46.8,1171.0
420,12000,12000,36 months,6.46,367.57,A1,Social Studies Teacher,6 years,RENT,38000.0,Dec-2018,Current,31.11,0.0,0.0,15.2,40761.0
440,20000,20000,60 months,16.14,487.86,C4,Instructor/Transporter/Job Coach,4 years,RENT,30000.0,Dec-2018,Current,41.84,0.0,1.0,49.0,34891.0
460,3000,3000,36 months,24.37,118.29,E2,Conductor,10+ years,MORTGAGE,80000.0,Dec-2018,Current,17.58,0.0,0.0,100.4,50416.0
480,4000,4000,36 months,7.02,123.55,A2,Receptionist,8 years,OWN,40000.0,Dec-2018,Current,12.63,0.0,0.0,5.0,13539.0
500,6000,6000,36 months,17.97,216.83,D1,Director of Fleet,5 years,MORTGAGE,90000.0,Dec-2018,Current,66.87,0.0,0.0,57.7,226523.0
520,4800,4800,36 months,10.72,156.52,B2,Realtor,10+ years,RENT,80000.0,Dec-2018,Current,26.55,0.0,0.0,70.3,66460.0
540,40000,40000,60 months,13.56,921.64,C1,Operations Manager,7 years,MORTGAGE,145000.0,Dec-2018,Current,20.00,0.0,1.0,56.4,121002.0
560,4000,4000,36 months,7.02,123.55,A2,Biology professor,10+ years,MORTGAGE,67000.0,Dec-2018,Current,16.01,0.0,0.0,23.6,16584.0
580,15000,15000,36 months,7.02,463.30,A2,NaN,< 1 year,MORTGAGE,60000.0,Dec-2018,Current,10.18,0.0,0.0,21.0,15844.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260080,12000,12000,60 months,13.59,276.68,C2,sales,10+ years,MORTGAGE,62000.0,Oct-2017,Current,7.41,0.0,1.0,15.4,30468.0
2260100,5100,5100,36 months,19.03,187.03,D3,"Carrier, and field representative",4 years,RENT,58000.0,Oct-2017,Charged Off,33.13,0.0,2.0,74.6,47254.0
2260120,10000,10000,60 months,16.02,243.29,C5,Fiber Splicer,2 years,MORTGAGE,130000.0,Oct-2017,Fully Paid,8.24,0.0,0.0,41.6,29422.0
2260140,12000,12000,60 months,18.06,305.12,D2,billing analist,2 years,RENT,60000.0,Oct-2017,Current,6.20,0.0,0.0,68.2,12895.0
2260160,25000,25000,60 months,12.62,563.98,C1,Management Services Officer I,10+ years,RENT,54260.0,Oct-2017,Current,38.48,0.0,0.0,41.5,58026.0
2260180,12000,12000,36 months,5.32,361.38,A1,International Managing Director,10+ years,MORTGAGE,150000.0,Oct-2017,Fully Paid,0.72,0.0,0.0,10.2,9022.0
2260200,4700,4700,36 months,7.97,147.22,A5,Sales Trainer,3 years,RENT,59000.0,Oct-2017,Fully Paid,19.49,1.0,0.0,25.2,34820.0
2260220,5000,5000,36 months,11.99,166.05,B5,WARRANTY ADMINISTRATOR,3 years,MORTGAGE,65000.0,Oct-2017,Current,27.09,0.0,1.0,50.7,51836.0
2260240,10000,10000,36 months,9.44,320.05,B1,Welder fitter leader,10+ years,RENT,90000.0,Oct-2017,Fully Paid,14.20,0.0,0.0,7.3,28844.0
2260260,20000,20000,36 months,9.44,640.10,B1,Director,10+ years,MORTGAGE,255000.0,Oct-2017,Current,1.45,1.0,0.0,96.0,8922.0
2260280,20000,20000,36 months,7.97,626.46,A5,Site Reliability Engineer,< 1 year,MORTGAGE,150000.0,Oct-2017,Current,21.42,0.0,0.0,69.8,67908.0
2260300,4200,4200,36 months,22.91,162.39,E1,porter,7 years,RENT,20668.0,Oct-2017,Charged Off,25.67,0.0,1.0,52.2,10177.0
2260320,30000,30000,36 months,16.02,1055.01,C5,Medicare D Advisor,3 years,RENT,78000.0,Oct-2017,Current,30.11,0.0,1.0,85.5,43247.0
2260340,16200,16200,36 months,23.88,634.56,E2,Mechanic,5 years,MORTGAGE,45000.0,Oct-2017,Current,6.16,0.0,1.0,32.3,5961.0
2260360,21800,21800,36 months,30.75,934.43,F5,Shop manager,6 years,MORTGAGE,56000.0,Oct-2017,Current,11.43,0.0,2.0,52.8,16752.0
2260380,11200,11200,36 months,9.44,358.46,B1,Phase 1 Tester,10+ years,RENT,34500.0,Oct-2017,Current,9.77,0.0,0.0,27.6,5435.0
2260400,16000,16000,36 months,9.93,515.75,B2,Legal secretary,10+ years,MORTGAGE,140000.0,Oct-2017,Current,27.15,0.0,1.0,67.1,115065.0
2260420,8500,8500,36 months,9.93,274.00,B2,Installer technician,4 years,RENT,125000.0,Oct-2017,Fully Paid,6.93,0.0,1.0,19.1,32616.0
2260440,35000,35000,36 months,24.85,1388.82,E3,NaN,NaN,MORTGAGE,30000.0,Oct-2017,Late (31-120 days),42.64,1.0,0.0,43.6,29096.0
2260460,20000,20000,36 months,18.06,723.66,D2,Member Service Rep,3 years,RENT,41000.0,Oct-2017,Current,25.38,0.0,0.0,59.1,31641.0
2260480,20000,20000,36 months,10.91,653.93,B4,Accountant,10+ years,OWN,64500.0,Oct-2017,Charged Off,18.30,1.0,0.0,40.3,21224.0
2260500,15000,15000,36 months,19.03,550.07,D3,Office Manager / Exec. Assistant,10+ years,RENT,82100.0,Oct-2017,Fully Paid,13.01,0.0,0.0,31.9,34299.0
2260520,10000,10000,36 months,18.06,361.83,D2,Conductor,10+ years,RENT,120000.0,Oct-2017,Late (31-120 days),3.09,0.0,0.0,64.8,4986.0
2260540,16500,16500,36 months,9.44,528.09,B1,Business Analyst,10+ years,MORTGAGE,150000.0,Oct-2017,Current,17.55,0.0,1.0,47.5,127028.0
2260560,35000,35000,36 months,19.03,1283.50,D3,NURSE SUPERVISOR,3 years,RENT,130000.0,Oct-2017,Current,7.87,7.0,1.0,37.1,9719.0
2260580,5000,5000,36 months,22.91,193.32,E1,Teacher,4 years,RENT,40000.0,Oct-2017,Fully Paid,26.37,0.0,2.0,66.7,18912.0
2260600,20000,20000,36 months,20.00,743.28,D4,Mechanical engineer,10+ years,RENT,70000.0,Oct-2017,Current,39.62,0.0,0.0,61.5,105517.0
2260620,11600,11600,36 months,17.09,414.10,D1,doorman,8 years,RENT,46535.0,Oct-2017,Charged Off,22.47,0.0,2.0,75.0,33442.0
2260640,20700,20700,60 months,12.62,466.98,C1,Dental Assistant,10+ years,OWN,46000.0,Oct-2017,Charged Off,27.05,0.0,0.0,33.0,33323.0
2260660,10000,10000,36 months,12.62,335.12,C1,Administrator,5 years,RENT,65000.0,Oct-2017,Current,4.41,0.0,0.0,87.9,11695.0

In [16]:
df.iloc[-1]

loan_amnt                    10000
funded_amnt                  10000
term                     36 months
int_rate                     12.62
installment                 335.12
sub_grade                       C1
emp_title            Administrator
emp_length                 5 years
home_ownership                RENT
annual_inc                   65000
issue_d                   Oct-2017
loan_status                Current
dti                           4.41
delinq_2yrs                      0
inq_last_6mths                   0
revol_util                    87.9
total_bal_ex_mort            11695
Name: 2260660, dtype: object

In [17]:
df["inflation"] = ""

As we need machine working to work with credit sub grades , we need to convert each sub grade value to integer from string, 
and by that we assigned each sub grade a value starting from 0 to 30, starting from F5 - A1

In [18]:
def gradetonum(subg):
    if subg=="A1":
        return 30
    elif subg=="A2":
        return 29
    elif subg=="A3":
        return 28
    elif subg=="A4":
        return 27
    elif subg=="A5":
        return 26
    elif subg=="B1":
        return 25
    elif subg=="B2":
        return 24
    elif subg=="B3":
        return 23
    elif subg=="B4":
        return 22
    elif subg=="B5":
        return 21
    elif subg=="C1":
        return 20
    elif subg=="C2":
        return 19
    elif subg=="C3":
        return 18
    elif subg=="C4":
        return 17
    elif subg=="C5":
        return 16
    elif subg=="D1":
        return 15
    elif subg=="D2":
        return 14
    elif subg=="D3":
        return 13
    elif subg=="D4":
        return 12
    elif subg=="D5":
        return 11
    elif subg=="E1":
        return 10
    elif subg=="E2":
        return 9
    elif subg=="E3":
        return 8
    elif subg=="E4":
        return 7
    elif subg=="E5":
        return 6
    elif subg=="F1":
        return 5
    elif subg=="F2":
        return 4
    elif subg=="F3":
        return 3
    elif subg=="F4":
        return 2
    elif subg=="F5":
        return 1
   

df["sub_grade"] = df["sub_grade"].apply(gradetonum)

In [19]:
df = df.dropna()

In [20]:
df.isnull().sum()

loan_amnt            0
funded_amnt          0
term                 0
int_rate             0
installment          0
sub_grade            0
emp_title            0
emp_length           0
home_ownership       0
annual_inc           0
issue_d              0
loan_status          0
dti                  0
delinq_2yrs          0
inq_last_6mths       0
revol_util           0
total_bal_ex_mort    0
inflation            0
dtype: int64

In [21]:
# Importing the necessary modules for Linear Regression
from sklearn import linear_model
lr = linear_model.LinearRegression()

In [22]:
from sklearn.model_selection import train_test_split

X = df[["loan_amnt","funded_amnt","int_rate","installment","annual_inc","dti","delinq_2yrs","inq_last_6mths","revol_util","total_bal_ex_mort"]]
y = df["sub_grade"]

# Split X and y into X_
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [23]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [24]:
# We can reach each coefficient of our features with coef_
lr.coef_

array([-3.17403506e-05, -3.17403483e-05, -1.25435862e+00,  2.14132766e-03,
        2.58125017e-08, -2.48827969e-03, -7.30710051e-02, -1.25041643e-01,
       -6.42142446e-03,  7.15383389e-07])

In [25]:
# And we can reach intercept point (a14) with intercept_
lr.intercept_

36.588385053916454

In [26]:
# Creating a for loop to check coefficients of features
for index, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, lr.coef_[0][index]))

IndexError: invalid index to scalar variable.

In [ ]:
lr.score(X_test, y_test)

In [ ]:
from sklearn.metrics import mean_squared_error

y_predict = lr.predict(X_test)

lr_mse = mean_squared_error(y_predict, y_test)

print(lr_mse)

In [ ]:
stats.ttest_1samp(df["annual_inc"],10)

In [ ]:
stats.ttest_ind(df["annual_inc"],df["sub_grade"],equal_var = False)  #did a p test , to see if there is a correlation 
#between annual income of a citizen and the subgrade for loan they took, and ttest approved our hypothesis.